---
- name: restart ssh
  action: service name=ssh state=restarted
  when: is_debian_or_ubuntu

- name: restart sshd
  action: service name=sshd state=restarted
  when: is_centos

- name: restart iptables-persistent
  action: service name=iptables-persistent state=restarted
  when: is_debian_or_ubuntu

- name: restart iptables
  action: service name=iptables state=restarted
  when: is_centos

- name: reload exports
  shell: exportfs -r

- name: ensure nfs-kernel-server service is running
  service: name=nfs-kernel-server state=started
  when: is_debian_or_ubuntu

- name: ensure nfs service is running
  service: name=nfs state=started
  when: is_centos

- name: restart nfs-kernel-server
  service: name=nfs-kernel-server state=restarted
  when: is_debian_or_ubuntu

- name: restart nfsd
  service: name=nfs state=restarted
  when: is_centos

- name: kill-HUP sshd
  shell: pkill -HUP sbin/sshd

- name: reboot
  command: /sbin/reboot